### ISSUE TITLE
"Back" button breadcrumb link doesn't work

### ISSUE THREAD

**Issue by philandstuff** [OllieJC/gotsecuritytxt.com#4]
## Expected

From a page for a particular site (eg https://gotsecuritytxt.com/query/gotsecuritytxt.com )
When I click on the "< Back" link
I expect to either go back in the browser history
  or go to the site top-level

## Actual

When I click the "< Back" link
Nothing happens
(except my browser URL gets an empty fragment `#` on the end of the URL)

Is there some broken/missing javascript? Does this even need to be javascript (a simple href to https://gotsecuritytxt.com/ would suffice, no?)

Happy to contribute a PR to fix, just need some direction on what the right fix is.

**Comment by OllieJC** [comment]
Cheers @philandstuff! I think this is broken because of the CSP I put in recently which blocks inline JS. I've been meaning to put a function in that will either go to the homepage or back in the history depending on how the user got there

**Comment by OllieJC** [comment]
I _fixed_ this, but not in the most ideal way, it now just displays a home button that goes back to the main page, regardless of whether you came from the GB sites etc. Tempted to remove the link altogether.. I'll close this but if you have any ideas, let me know! Thanks!
